name: Deploy to prod

on:
  push:
    branches: [repro]

jobs:
  publish:
    name: Publish to DockerHub
    environment: prod
    runs-on: ubuntu-latest
    env:
      ImageOS: ubuntu20

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
  
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vox:${{ github.sha }}
          context: .
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/vox:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          if: false
    
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vox:${{ github.sha }}
          context: .
          push: true


